### PR TITLE
Add `thrift_sasl` as a dependency

### PR DESCRIPTION
**Pull request by ZeroCool2u**
Add `thrift_sasl` as a dependency to ensure kerberos support is available. This is usually installed as a optional dependency via pip for impyla e.g. `pip install impyla[kerberos]`, but conda does not have the concept of optional dependencies yet.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ZeroCool2u** [comment]
@conda-forge-admin, please rerender

**Comment by ZeroCool2u** [comment]
@conda-forge-admin, please rerender

**Comment by ZeroCool2u** [comment]
Hi, @mariusvniekerk @wesm @kszucs would someone mind taking a look at this? Would be helpful for the Ibis project. If there's a good reason not to include it in the feedstock that's alright too and we can close the PR.

**Comment by mariusvniekerk** [comment]
Yeah seems reasonable.

**Comment by ZeroCool2u** [comment]
@mariusvniekerk Thanks!

**Comment by mariusvniekerk** [comment]
If you want to be a maintainer on this feedstock please add yourself. I'm no longer really in the position to make any statements on impyla

**Pull request merged**
